### PR TITLE
voodoo diffusers

### PR DESCRIPTION
**Pull request by monophthongal**
Hi,

This draft PR is an attempt to get voodoo working with the diffusers inpainting pipeline.

It works on my single thread worker with voodoo enabled, a Tesla T4 and 16GB system RAM - but needs more testing to ensure it works as expected and doesn't break anything on other systems and configurations.

Unlike Compvis-style models which are just PyTorch modules, diffusers "pipelines" are Python classes that load multiple PyTorch modules into class properties. So the PR runs the `extract_tensors` and `replace_tensors` functions on each module separately.

Since this approach makes use of a recently added diffusers feature (the `components` property, to list the pipeline's modules), the PR also bumps diffusers to the latest version. As far as I can tell, the newer version doesn't break anything.

Upgrading diffusers probably has the side effect of enabling xformers for inpainting, since diffusers recently added support for it.

Let me know what you think and if there are issues that need fixed.

### CODE REVIEW

**Comment by db0** [comment]
Awesome! Can't wait!

**Comment by db0** [comment]
@monophthongal So this code should be working currently?

**Comment by monophthongal** [comment]
That would be great! It should work, but I’ve only tested it on a small worker.

Things I think need verified before merging:

- how it works with multiple models loaded at the same time / multiple threads and whether this actually improves inpainting performance
- full precision
- whether it still works with voodoo disabled

**Comment by db0** [comment]
Great, I'm a bit busy atm so I'll if some of the community can test

**Comment by andersosthus** [comment]
I've ran my worker with this PR and it seems mostly OK so far.
I've been running with 4 models (`Seek.art MEGA`, `Midjourney Diffusion`, `stable_diffusion`, `stable_diffusion_inpainting`), `queue_size: 1`, `max_threads: 1`.

The one issue I've noticed is that I submitted a bad inpainting job apparently and I get the error listed below. Even after putting my worker in `maintenance mode`, I get the error every 5 minutes or so, so it looks like the job is still around somewhere getting retried.

Error:
```
2022-12-28 16:14:46.155 | WARNING  | worker.job:get_job_from_server:118 - During gen pop, server https://stablehorde.net responded with status code 403: This worker has been put into maintenance mode by its owner. Waiting for 10 seconds...
2022-12-28 16:14:56.718 | DEBUG    | worker.job:get_job_from_server:90 - Job pop took 0.45276
2022-12-28 16:14:56.718 | DEBUG    | __main__:pop_job:169 - Got a new job from the horde for model: stable_diffusion_inpainting
2022-12-28 16:14:56.718 | DEBUG    | __main__:bridge:111 - Starting job for model: stable_diffusion_inpainting
2022-12-28 16:14:56.718 | DEBUG    | __main__:bridge:113 - job submitted
2022-12-28 16:14:56.718 | DEBUG    | worker.job:start_job:144 - Starting job in threadpool
2022-12-28 16:14:56.719 | DEBUG    | worker.job:start_job:256 - inpainting (stable_diffusion_inpainting) request with id 80ff35f3-2832-4c37-94e8-1d0f40cf21b3 picked up. Initiating work...
2022-12-28 16:14:56.723 | WARNING  | worker.job:start_job:323 - inpainting image doesn't have an alpha channel. Aborting gen
2022-12-28 16:14:58.886 | DEBUG    | worker.job:get_job_from_server:90 - Job pop took 2.05781
2022-12-28 16:14:58.886 | DEBUG    | __main__:pop_job:169 - Got a new job from the horde for model: stable_diffusion
2022-12-28 16:14:58.886 | DEBUG    | __main__:bridge:125 - Job finished successfully in 2.156s (Total Completed: 147)
2022-12-28 16:14:58.915 | DEBUG    | __main__:bridge:111 - Starting job for model: stable_diffusion
2022-12-28 16:14:58.915 | DEBUG    | __main__:bridge:113 - job submitted
2022-12-28 16:14:58.915 | DEBUG    | worker.job:start_job:144 - Starting job in threadpool
2022-12-28 16:14:58.916 | DEBUG    | worker.job:start_job:256 - inpainting (stable_diffusion) request with id 6bbd3edc-9f06-4881-ae91-a649fdfccee2 picked up. Initiating work...
2022-12-28 16:14:58.920 | DEBUG    | worker.job:start_job:338 - Starting generation...
2022-12-28 16:14:58.920 | DEBUG    | nataili.inference.diffusers.inpainting:generate:127 - <PIL.WebPImagePlugin.WebPImageFile image mode=RGB size=512x512 at 0x1B4A02965E0>
2022-12-28 16:14:59.501 | DEBUG    | worker.job:get_job_from_server:90 - Job pop took 0.315966
2022-12-28 16:14:59.502 | WARNING  | worker.job:get_job_from_server:118 - During gen pop, server https://stablehorde.net responded with status code 403: This worker has been put into maintenance mode by its owner. Waiting for 10 seconds...
2022-12-28 16:14:59.218 | ERROR    | concurrent.futures.thread:run:57 - An error has been caught in function 'run', process 'MainProcess' (65404), thread 'ThreadPoolExecutor-0_0' (61704):
Traceback (most recent call last):

  File "D:\horde\conda\envs\windows\lib\threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
    |    -> <function Thread._bootstrap_inner at 0x000001B4F506D280>
    -> <Thread(ThreadPoolExecutor-0_0, started daemon 61704)>

  File "D:\horde\conda\envs\windows\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
    |    -> <function Thread.run at 0x000001B4F506CF70>
    -> <Thread(ThreadPoolExecutor-0_0, started daemon 61704)>

  File "D:\horde\conda\envs\windows\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
    |    |        |    |        |    -> {}
    |    |        |    |        -> <Thread(ThreadPoolExecutor-0_0, started daemon 61704)>
    |    |        |    -> (<weakref at 0x000001B49DF0FCC0; to 'ThreadPoolExecutor' at 0x000001B49A22D340>, <_queue.SimpleQueue object at 0x000001B49A22...
    |    |        -> <Thread(ThreadPoolExecutor-0_0, started daemon 61704)>
    |    -> <function _worker at 0x000001B4F508A700>
    -> <Thread(ThreadPoolExecutor-0_0, started daemon 61704)>

  File "D:\horde\conda\envs\windows\lib\concurrent\futures\thread.py", line 80, in _worker
    work_item.run()
    |         -> <function _WorkItem.run at 0x000001B4F508A820>
    -> <concurrent.futures.thread._WorkItem object at 0x000001B75E3C4B20>

> File "D:\horde\conda\envs\windows\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
             |    |   |    |       |    -> {}
             |    |   |    |       -> <concurrent.futures.thread._WorkItem object at 0x000001B75E3C4B20>
             |    |   |    -> [{'payload': {'prompt': 'beautiful', 'ddim_steps': 30, 'n_iter': 1, 'sampler_name': 'k_euler', 'cfg_scale...
             |    |   -> <concurrent.futures.thread._WorkItem object at 0x000001B75E3C4B20>
             |    -> <bound method HordeJob.start_job of <worker.job.HordeJob object at 0x000001B75E3C4A60>>
             -> <concurrent.futures.thread._WorkItem object at 0x000001B75E3C4B20>

  File "D:\horde\worker\job.py", line 339, in start_job
    generator.generate(**gen_payload)
    |         |          -> {'prompt': 'beautiful', 'height': 512, 'width': 512, 'seed': '3792712469', 'n_iter': 1, 'batch_size': 1, ...
    |         -> <function inpainting.generate at 0x000001B49A1339D0>
    -> <nataili.inference.diffusers.inpainting.inpainting object at 0x000001B75E3C4310>

  File "D:\horde\nataili\inference\diffusers\inpainting.py", line 167, in generate
    with load_diffusers_pipeline_from_plasma(self.pipe, self.device) as pipe:
         |                                   |    |     |    -> device(type='cuda', index=0)
         |                                   |    |     -> <nataili.inference.diffusers.inpainting.inpainting object at 0x000001B75E3C4310>
         |                                   |    -> ObjectRef(008dba0c68dc5c92f0504fe96bbb1b37b1f1b4f80100000003000000)
         |                                   -> <nataili.inference.diffusers.inpainting.inpainting object at 0x000001B75E3C4310>
         -> <function load_diffusers_pipeline_from_plasma at 0x000001B4979469D0>

  File "D:\horde\conda\envs\windows\lib\contextlib.py", line 113, in __enter__
    return next(self.gen)
                |    -> <generator object load_diffusers_pipeline_from_plasma at 0x000001B4A12D0F90>
                -> <contextlib._GeneratorContextManager object at 0x000001B4A0296250>

  File "D:\horde\nataili\util\voodoo.py", line 84, in load_diffusers_pipeline_from_plasma
    for name, weights in modules.items():
                         -> [{'params': {}, 'buffers': {'betas': array([0.00085  , 0.0008545, 0.0008593, 0.000864 , 0.000869 , 0.0008736,
                                   0.000878...

AttributeError: 'list' object has no attribute 'items'
2022-12-28 16:15:09.584 | ERROR    | __main__:bridge:122 - Job failed with exception, 'list' object has no attribute 'items'
2022-12-28 16:15:09.586 | ERROR    | __main__:bridge:123 - 'list' object has no attribute 'items'
NoneType: None
2022-12-28 16:15:09.587 | DEBUG    | __main__:bridge:125 - Job finished successfully in 10.671s (Total Completed: 148)
```

**Comment by db0** [comment]
What do you mean by a "bad inpainting job"? Generally no job should crash the worker like that.

**Comment by andersosthus** [comment]
Don't really know how it happened. I used https://aqualxx.github.io/stable-ui/ to create the inpainting job from one of my previously generated images. Not sure what went wrong though, because all other jobs I submitted worked fine.

**Comment by andersosthus** [comment]
I've also observed the following in my logs, but not sure if that's related to this or a more generic error:

```
ERROR      | 2022-12-28 20:35:16.748585 | worker.job:start_job:345 - Something went wrong when processing request.
Please inform the developers of the below payload:
{'prompt': 'splash art of a hiker looking out over a lake', 'height': 512, 'width': 960, 'seed': '641112103', 'n_iter': 1, 'batch_size': 1, 'save_individual_images': False, 'ddim_steps': 80, 'cfg_scale': 7.0, 'inpaint_img': <PIL.WebPImagePlugin.WebPImageFile image mode=RGB size=960x512 at 0x24B92679F40>, 'inpaint_mask': <PIL.WebPImagePlugin.WebPImageFile image mode=RGB size=960x512 at 0x24B926796A0>, 'request_type': 'inpainting', 'model': 'stable_diffusion_inpainting'}
DEBUG      | 2022-12-28 20:35:16.765206 | __main__:bridge:125 - Job finished successfully in 5.000s (Total Completed: 95)
```

**Comment by db0** [comment]
You should be able to see the stack trace in trace.log. See what the error message at the same time is

**Comment by andersosthus** [comment]
> You should be able to see the stack trace in trace.log. See what the error message at the same time is

It was an out-of-memory error. It seems like the Voodoo Diffuser inpainting pipeline requires more VRAM, because I don't have any OOM errors when running from the main branch.

**Comment by monophthongal** [comment]
Thanks for testing! I’ll see if I can reproduce these issues and figure out what’s causing them.

**Comment by monophthongal** [comment]
OK, I forgot to reenable attention slicing for the PR. This is key for memory management so would likely cause the OOM error.

For @andersosthus, my guess is the invalid inpainting job is causing nataili to fallback to a compvis model and then incorrectly try to pass that to the inpainting generator.

**Comment by andersosthus** [comment]
> OK, I forgot to reenable attention slicing for the PR. This is key for memory management so would likely cause the OOM error. I added it back.

Thanks, I'll try to run the worker again tomorrow and see if attention slicing fixes the OOM issues I've seen.

That being said, (and this might not belong here in this PR), but I would think a better error reporting would be to surface the CUDA error up to the main output window.

Right now, the main window gave me:
```
ERROR      | 2022-12-28 20:35:16.748585 | worker.job:start_job:345 - Something went wrong when processing request.
Please inform the developers of the below payload:
{'prompt': 'splash art of a hiker looking out over a lake', 'height': 512, 'width': 960, 'seed': '641112103', 'n_iter': 1, 'batch_size': 1, 'save_individual_images': False, 'ddim_steps': 80, 'cfg_scale': 7.0, 'inpaint_img': <PIL.WebPImagePlugin.WebPImageFile image mode=RGB size=960x512 at 0x24B92679F40>, 'inpaint_mask': <PIL.WebPImagePlugin.WebPImageFile image mode=RGB size=960x512 at 0x24B926796A0>, 'request_type': 'inpainting', 'model': 'stable_diffusion_inpainting'}
DEBUG      | 2022-12-28 20:35:16.765206 | __main__:bridge:125 - Job finished successfully in 5.000s (Total Completed: 95)
```

while in my `trace.log` I found the actual issue:
``` 
TRACE      | 2022-12-28 21:01:12.173254 | worker.job:start_job:350 - Traceback (most recent call last):
  File "D:\horde\worker\job.py", line 339, in start_job
    generator.generate(**gen_payload)
  File "D:\horde\nataili\inference\diffusers\inpainting.py", line 173, in generate
    x_samples = pipe(
  File "D:\horde\conda\envs\windows\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
  --- Stack Trace removed by me ---

torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 1.76 GiB (GPU 0; 10.00 GiB total capacity; 8.83 GiB already allocated; 0 bytes free; 8.92 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

> For @andersosthus, my guess is the invalid inpainting job is causing nataili to fallback to a compvis model and then incorrectly try to pass that to the inpainting generator somehow.

I believe the reason for the invalid inpainting jobs is a bug in the web frontend I used to test with. We observed some other issues as well with inpainting, so I'm guessing there are some edge-case bugs in that UI.

**Comment by andersosthus** [comment]
I've done some testing with the updated code, and I don't have any OOM issues so far when doing inpainting up to 1024x1024.

Another thing I've noticed is that if I set steps to 30 when submitting the inpainting job, my worker only does 23 iterations. Likewise, if I set steps to 50, my worker only does 38 iterations. Not sure if this is expected or not, just an observation.

**Comment by db0** [comment]
Yes, you're supposed to use trace.log as the stdout can get very busy with the progress bars, especially with multiple threads, which can make the stack trace unreadable

**Comment by monophthongal** [comment]
> Another thing I've noticed is that if I set steps to 30 when submitting the inpainting job, my worker only does 23 iterations. Likewise, if I set steps to 50, my worker only does 38 iterations. Not sure if this is expected or not, just an observation.
Are you sure these are being sent as inpainting requests? That's normal for img2img (50 steps * 0.75 denoising strength = ~38 steps) but inpainting doesn't do that as far as I know.

This PR doesn't actually change anything significant about how inpainting is performed, just how the model is loaded.

**Comment by monophthongal** [comment]
OK, moving out of draft. Spent some time today testing this on a Tesla T4, an A100 40GB, and in Google Colab in various configurations. As far as I can tell it's working as expected. I also added a fix for the exception thrown on invalid inpainting requests.

**Comment by db0** [comment]
great. I'll see if we can get some more testers and then merge. Great work! Join us on discord to get some well deserved Kudos!

**Comment by andersosthus** [comment]
> > Another thing I've noticed is that if I set steps to 30 when submitting the inpainting job, my worker only does 23 iterations. Likewise, if I set steps to 50, my worker only does 38 iterations. Not sure if this is expected or not, just an observation.
> 
> Are you sure these are being sent as inpainting requests? That's normal for img2img (50 steps * 0.75 denoising strength = ~38 steps) but inpainting doesn't do that as far as I know.

Yeah, it was the client that had denoising strength set to 0.75 as default, I just didn't notice that, so all good.

> great. I'll see if we can get some more testers and then merge. Great work! Join us on discord to get some well deserved Kudos!

I've been running this a few times and I haven't seen any crashes after the last updates.

**Comment by monophthongal** [comment]
awesome!

> great. I'll see if we can get some more testers and then merge. Great work! Join us on discord to get some well deserved Kudos!

I'm cogentdev on discord.

**Pull request merged**
