### PR TITLE
v0.2.0

### PR DESCRIPTION
**Pull request by hlky**
Breaking changes.

Stable Horde worker can now be moved to its own repo, and install Nataili as a package

### CODE REVIEW

**Comment by hlky** [comment]
@db0 horde worker is not included in this branch, will require some small changes, I can do this if you want

**Comment by hlky** [comment]
Yes, `pip install .` or `pip install nataili` (not published to pypi yet) will install the dependencies. Anything in requirements.txt is installed. 
```
[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}
```
Only issue is torch, it may install cpu version, will test again on a fresh venv. Specifying `--extra-index-url` in requirements.txt gives an error, I'm not sure how to set the extra index url with pyproject.toml

I've set it to `torch>=1.12.0+cu113` but without the extra index url it will probably still install cpu version

---

With regards to horde bridge, check the new [README](https://github.com/Sygil-Dev/nataili/blob/v0.2.0/README.md).
Main differences will be imports, a lot of things can imported directly from `nataili`, or from the subpackage itself `nataili.util` rather than something like `nataili.util.process_prompt_tokens`

---

You can continue to use `ModelManager` but this is now the Super ModelManager class, and you have to access each service like `mm.blip`, each service has a `load()` function and they're using the same keys as before.
You can use the individual service ModelManagers instead

Model json's are split, and included in the package, can add back in the download from online reference functionality, or just release a new version of the package when there are new models, we don't get new ones *that* often so it would work imo.

You no longer need to manually check if a model is available/downloaded, if you call `load()` on a model that isn't downloaded, it is downloaded by `load()` function

---

There haven't been any changes to the services themselves, with the exception of CLIP interrogate, which now caches the text/image embeds to be re-used. CLIP Interrogate is slow because it computes thousands of text embeds every time. VRAM usage of CLIP is controlled by batch size, the caching is using batch size 1 currently, just simpler and keeps VRAM requirements to the absolute minimum. Once text embeds are cached, CLIP interrogate is incredibly fast. If the lists get more words added, just the extra embeds are computed. Lists are still static for now, and included in the packages' files.
Windows users will experience issues with this, because Windows Defender's Real-time protection freaks out over the thousands of tiny files, we will need to document this and recommend adding `~/.cache/nataili/embeds` to the exclusions. It still works, but very slowly because Windows Defender is scanning each file.

https://user-images.githubusercontent.com/106811348/210182950-4aa0c264-a4b5-4fdd-b026-b598cd9af6cc.mp4

---

CodeFormers was a weird one, I had to include modified versions of their stuff to add cache dir support. It's a small thing really, but I do want every model used to be cacheable to a specified directory, instead of wherever the devs decide it's going to be.
GFPGAN required similar changes to add support for a cache dir, specifically for `detection_Resnet50_Final.pth` and `parsing_parsenet.pth`  - previously we had to just let them download to `./gfpgan/weights`

CodeFormers seems to be affected by the long generation time bug again, so I will investigate, I suspect this is an issue with the CodeFormers class itself rather than something we have introduced.

---

Another thing to note - model entries no longer require a path, I may be able to remove `file_path` from `download` completely.

Models are downloaded to `~/.cache/nataili/<service>/` so there's no need to specify a relative path in the json

image

---

Diffusers models haven't been included, I didn't really like the implementation, I would rather explicitly download the model files than rely on diffusers. Otherwise you can't cache/download the model without trying to load the model. I'm not a fan of huggingface's cache structure either.

image

I will implement inpainting and depth model with the CompVis version instead. Plus the Stability Super Resolution model.

Non-768 2.x needs adding too.

---

AITemplate is untested, I made some changes to try and avoid the AITemplate Pipeline pulling in the entire diffusers model, it doesn't need to, but AITemplate doesn't work on Windows, so I haven't got round to testing it yet

**Comment by db0** [comment]
Quite big changes. It will take me a while to set up a new repo and validate everything works, but we also need to ensure the existing functionality works, so we need to have inpainting and depth2img before merging as well.

So I'm guessing we're not going to be supporting diffusers at all now? I am concerned by this as a lot of cutting edge development is happening through diffusers and a lot of new models are coming out only as diffusers now. Using diffusers is the main way others managed to onboard new functionality so I don't quite think it's a good idea to scrap all the work people did to support them. For me it makes sense to support them as this gives us more opening to support more functionalities.

**Comment by db0** [comment]
We should also tag the current version before we merge. This will allow people who can't switch as fast to use the old version

**Comment by hlky** [comment]
`we need to have inpainting and depth2img`
Yes, I'll port the compvis code over.

`cutting edge development is happening through diffusers`
Such as?
I haven't seen anything that is exclusively diffusers, and if there is, it's not actually exclusive to diffusers, there's no reason it can't be CompVis too.
I think you will find most development happens external to diffusers, then diffusers implement it and force their own changes/make it incompatible with the original (see textual inversion).

`new models are coming out only as diffusers now`
Such as? Conversion is trivial anyway.

`diffusers is the main way others managed to onboard new functionality`
Yes, because literally just using the diffusers pipeline is easier than porting the [CompVis code](https://github.com/Stability-AI/stablediffusion). However Nataili isn't meant to be a wrapper for diffusers pipelines, and diffusers pipelines are just bad.

I would prefer to implement actual model management for diffusers, and have a unified pipeline. Halffried's grpcserver has a good unified diffusers pipeline with improved inpainting/outpainting, not sure if they have depth implemented.

`we are onboarding new models almost practically daily, so it makes sense to keep the model reference external`
If model onboarding pace is going to exceed development of releases and models will be added literally every day, then yes, keep it external. If model onboarding is likely to only be a couple of times a week, a regular release pattern should suffice.

**Comment by db0** [comment]
> If model onboarding pace is going to exceed development of releases and models will be added literally every day, then yes, keep it external. If model onboarding is likely to only be a couple of times a week, a regular release pattern should suffice.

No it's still better to keep the model reference external, because we can load new models during runtime, without having to restart workers. If we put the model reference only in this repo, then we force workers to have to pip upgrade and restart all the time just to get new models

**Comment by hlky** [comment]
Will rewrite the existing `download_model_reference()` to support the split model reference, and save the files under `~/.cache/nataili`

Model references should be included in the package, in case the online source is unavailable. Submodule or just a GitHub action to keep the repos in sync? either is fine imo

**Comment by db0** [comment]
Ye that was the approach already. We can figure an automatic way or just manual sync now and then. It's not so important for the local version to contain each new dreambooth immediately imho.

**Pull request merged**
