### PR TITLE
mo-di-diffusion model and CreativeML OpenRAIL-M

### PR DESCRIPTION
**Pull request by ddrmaster1000**
Adding the mo-di-diffusion model. 
The mo-di-diffusion model and trinart model are licensed under the CreativeML OpenRAIL License which specifies among other things:
"You may re-distribute the weights and use the model commercially and/or as a service. If you do, please be aware you have to include the same use restrictions as the ones in the license and share a copy of the CreativeML OpenRAIL-M to all your users (please read the license entirely and carefully) [Please read the full license here](https://huggingface.co/spaces/CompVis/stable-diffusion-license)" - https://huggingface.co/spaces/CompVis/stable-diffusion-license

I added a small bit of text to the read me which should satisfy the condition of the users being aware of the license.

### CODE REVIEW

**Comment by db0** [comment]
Great. Any chance you can include the md5sum as well? Do you know how?

**Comment by ddrmaster1000** [comment]
Sure, I can do that.

**Comment by hlky** [comment]
This is `modern disney diffusion`.

**Comment by hlky** [comment]
@ddrmaster1000 can you update the `file_url` of the existing entry instead?

@db0 the repo was renamed for obvious reasons. The key and `name` of entry should probably be changed too for the same reason.

**Comment by ddrmaster1000** [comment]
I do not see any pre-existing file for ```modern disney diffusion```. Are you saying you would like me to rename mo-di to modern disney?

**Comment by db0** [comment]
Oh? I didn't realized they renamed their model

**Comment by ddrmaster1000** [comment]
Just changed the bridgeData_template with the mo-di-diffusion name and added the MD5.

**Comment by db0** [comment]
Ah I just realized where we are. You need to update the [model reference repository](https://github.com/Sygil-Dev/nataili-model-reference). This db file is just the fallback in case of network issues. 

I'm merge this request but you won't see this new name until we update it there as well. That one already has a Modern Disney, so you can just rename it.

**Pull request merged**
