### PR TITLE
Enabled attention slicing

### PR DESCRIPTION
**Pull request by blueturtleai**
**This change should be tested first to see, if there are real benefits and if side effects occur.**

This changes enables attention slicing. When this option is enabled, the attention module will split the input tensor in slices, to compute attention in several steps. This is useful to save some memory in exchange for a small speed decrease.

https://huggingface.co/docs/diffusers/v0.3.0/en/api/pipelines/stable_diffusion#diffusers.StableDiffusionInpaintPipeline.enable_attention_slicing

### CODE REVIEW

**Comment by db0** [comment]
Ah you didn't mention the speed decrease. If this impacts speed, it should be made optional via a cli arg.

**Comment by blueturtleai** [comment]
Okay. Did you try it? Did it help decreasing needed memory? If this isn’t the case, I think it doesn’t make sense to add it at all.

**Comment by db0** [comment]
Not yet. I need to find the time

**Comment by db0** [comment]
Not only did I not get any slowdown, I even got a speedup as I had some RAM buffer. Good job! Can you please rebase to the latest main which changed the style around and then we can merge

**Comment by db0** [comment]
This is very good. It allows me to run inpainting with other models! 

Did you close by mistake?

**Pull request closed without merging**
