### PR TITLE
Feature code linters: black, flake8, isort with github actions

### PR DESCRIPTION
**Pull request by leszekhanusz**
## Install dev dependencies:

- `pip install -r requirements.dev.txt`

## Check your code:

- `style.sh`

## Fix your code locally:

- `style.sh --fix`

### CODE REVIEW

**Comment by db0** [comment]
Adding argparser after the imports will break the code as we need the argparser arguments to set disable xformers and voodoo as they're being imported.

**Comment by leszekhanusz** [comment]
> Adding argparser after the imports will break the code as we need the argparser arguments to set disable xformers and voodoo as they're being imported.

Right, I put some of the imports back down. I don't really like that way of doing imports with global variables but that should be probably fixed in another PR.

**Comment by db0** [comment]
They're not really global variables though. They're imported classes specifically for this purpose. I guess there may be better option but that would need some refactoring on code I didn't write.

**Comment by leszekhanusz** [comment]
> They're not really global variables though. They're imported classes specifically for this purpose. I guess there may be better option but that would need some refactoring on code I didn't write.

I'll do it

**Comment by db0** [comment]
Hm, we could use a `style.cmd`

**Comment by db0** [comment]
Yes. I should switch at some point but too much other stuff to do atm to think about reinstalling

**Pull request merged**
