### PR TITLE
SD2 Depth2Img Implementation

### PR DESCRIPTION
**Pull request by ResidentChief**
Can't do stylefix on my machine for some reason so that needs doing as well

### CODE REVIEW

**Comment by db0** [comment]
can you run `style.cmd--fix` please and fix the issues?

**Comment by monophthongal** [comment]
This is great!

Not needed for this PR, but at some point it would probably be worth moving the duplicate code from the separate diffusers-based generators into a base class. Especially if there's interest in supporting other pipelines in the future.

**Comment by db0** [comment]
Looks like 25.1 doesn't work

```
ImportError: You need to install `transformers` from 'main' in order to use StableDiffusionDepth2ImgPipeline: 
```
 pip install git+https://github.com/huggingface/transformers
```
Exception in thread Thread-43:
 90%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                 | 45/50 [00:07<00:01,  3.17it/s]Traceback (most recent call last):
  File "C:\Projects\henk-nataili\conda\envs\windows\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\Projects\henk-nataili\conda\envs\windows\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Projects\henk-nataili\conda\envs\windows\lib\site-packages\loguru\_logger.py", line 1220, in catch_wrapper
    return function(*args, **kwargs)
  File "C:\Projects\henk-nataili\worker\bridge_data.py", line 322, in _reload_models
    success = model_manager.load_model(model)
  File "C:\Projects\henk-nataili\nataili\model_manager.py", line 492, in load_model
    self.loaded_models[model_name] = self.load_diffuser(model_name)
  File "C:\Projects\henk-nataili\nataili\model_manager.py", line 424, in load_diffuser
    pipe = StableDiffusionDepth2ImgPipeline.from_pretrained(
  File "C:\Projects\henk-nataili\conda\envs\windows\lib\site-packages\diffusers\utils\dummy_torch_and_transformers_objects.py", line 94, in from_pretrained
    requires_backends(cls, ["torch", "transformers"])
  File "C:\Projects\henk-nataili\conda\envs\windows\lib\site-packages\diffusers\utils\import_utils.py", line 372, in requires_backends
    raise ImportError(
ImportError: You need to install `transformers` from 'main' in order to use StableDiffusionDepth2ImgPipeline:
```
 pip install git+https://github.com/huggingface/transformers
 ```

**Comment by db0** [comment]
Let's switch back to git fot now, and we can pin it again when it is released

**Comment by db0** [comment]
Switched to the main branch for transformers. Got an error when fulfilling a normal 2.1 request

```
Please inform the developers of the below payload:
{'prompt': 'Sharp detail,, Soft front light, photorealistic,  vivid autumn, under oak, Emma Watson, ahegao, ((young)) woman, plump ass, slim body, ((Skintight)) lace, string, redhead, wavy messy hair, folded arms, ((topless)), nude above, bare above navel, (legs apart),  ### Doll, 2 head, 3 arm, old, ugly, 3d, thick, 2 body, big breast, disfigured, mutation, monochrome ', 'height': 512, 'width': 512, 'seed': '2802737954', 'n_iter': 1, 'batch_size': 1, 'save_individual_images': False, 'save_grid': False, 'ddim_steps': 50, 'sampler_name': 'dpmsolver_karras', 'cfg_scale': 8.0, 'request_type': 'txt2img', 'model': 'stable_diffusion_2.1'}
TRACE      | 2022-12-30 16:08:23.357911 | worker.job:start_job:387 - Traceback (most recent call last):
  File "C:\Projects\henk-nataili\worker\job.py", line 376, in start_job
    generator.generate(**gen_payload)
  File "C:\Projects\henk-nataili\nataili\util\voodoo.py", line 30, in wrapper
    return torch.cuda.amp.autocast()(torch.no_grad()(f))(*args, **kwargs)
  File "C:\Projects\henk-nataili\conda\envs\windows\lib\site-packages\torch\amp\autocast_mode.py", line 14, in decorate_autocast
    return func(*args, **kwargs)
  File "C:\Projects\henk-nataili\conda\envs\windows\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "C:\Projects\henk-nataili\nataili\inference\compvis.py", line 304, in generate
    with load_from_plasma(self.model, self.device) as model:
  File "C:\Projects\henk-nataili\conda\envs\windows\lib\contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "C:\Projects\henk-nataili\nataili\util\voodoo.py", line 72, in load_from_plasma
    skeleton.eval().to(device, memory_format=torch.channels_last)
  File "C:\Projects\henk-nataili\conda\envs\windows\lib\site-packages\lightning_lite\utilities\device_dtype_mixin.py", line 54, in to
    return super().to(*args, **kwargs)
  File "C:\Projects\henk-nataili\conda\envs\windows\lib\site-packages\torch\nn\modules\module.py", line 987, in to
    return self._apply(convert)
  File "C:\Projects\henk-nataili\conda\envs\windows\lib\site-packages\torch\nn\modules\module.py", line 639, in _apply
    module._apply(fn)
  File "C:\Projects\henk-nataili\conda\envs\windows\lib\site-packages\torch\nn\modules\module.py", line 639, in _apply
    module._apply(fn)
  File "C:\Projects\henk-nataili\conda\envs\windows\lib\site-packages\torch\nn\modules\module.py", line 639, in _apply
    module._apply(fn)
  [Previous line repeated 4 more times]
  File "C:\Projects\henk-nataili\conda\envs\windows\lib\site-packages\torch\nn\modules\module.py", line 662, in _apply
    param_applied = fn(param)
  File "C:\Projects\henk-nataili\conda\envs\windows\lib\site-packages\torch\nn\modules\module.py", line 985, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
NotImplementedError: Cannot copy out of meta tensor; no data!
```

**Comment by db0** [comment]
Continued in #92

**Pull request closed without merging**
