### PR TITLE
Enable optionally specifying a cache directory.

### PR DESCRIPTION
**Pull request by tazlin**
See #102. 
@db0 

`nataili\cache\cache.py` has a new function in this pull request, `get_cache_directory()`. This enables (optionally) changing the cache directory when users specify the `XDG_CACHE_HOME` environment variable. Otherwise, the previous behavior of using `~/.cache/` is used. It is my view that `~/.cache/` is overly generic and confusing to end users, but that's an issue for another time. In the interest of something resembling backwards compatibility, I have left the default behavior to be `~/.cache/`.

`get_cache_directory()` has been appropriately implemented throughout the project, where paths are constructed, to support this behavior. Any reference to `.cache/` or calls to `Path.home()` when constructing paths are included in this, and I specifically looked through major entry points for evidence of reliance on the home directory. 

If there was subtle and/or assumed reliance on the `~/.cache/` directory, it is very likely I missed it. However, I did test my revision with the AI-Horde-Worker, and it acted as expected, where `XDG_CACHE_HOME` was specified using that directory, and `~/.cache/` if not.

**Please note** that `nataili\train\dataset\EveryDream\latent_cache.py` was not updated in this pull request, despite reference `.cache`, as I could not discriminate the intended behavior of `LatentCacheManger`'s init function, `def __init__(self, latent_cache_path="/.cache/latents", device=torch.device("cuda"), jitter_lim=8, vae=None):`, as it appears to expect to operate in the working directory (no path construction). Further, `LatentCacheManger` is never instantiated in a way I could easily detect within the scope of the project, so I have no working basis to guess.

### CODE REVIEW

**Comment by tazlin** [comment]
This is a disruptive change for anyone who will have used a previous version to this PR and already had `XDG_CACHE_HOME` defined. From their perspective, the models will have 'disappeared' and they will redownload. Is there a preferred way to go about addressing this?

**Comment by hlky** [comment]
Re: disruptive change. I don't think anyone is using this version atm, horde worker is still using v0.0.1 for now

**Comment by tazlin** [comment]
I was unclear if there was a wider audience for this. If this is mostly horde worker using this code base, then I suspect this will be minimally disruptive.

**Comment by hlky** [comment]
@tazlin Thank you for your contribution. I appreciate it.

**Comment by db0** [comment]
Thanks peeps!

**Pull request merged**
